### ISSUE TITLE
WebGL build not working by default

### ISSUE THREAD

**Issue by dhawalbanker** [atteneder/glTFastDemo#3]
Hello there, 
While exploring the glTFast and glTFDemo, I want to develop WebGL build for the same. I am able to build the WebGL output, but for some reason, the Main scene doesn't load. The chrome/firefox console doesn't even spew any errors. 

While building for WebGL, I do see a warning that "Script attached to SceneSelection is missing". 

Are there any build instructions or documents or wiki? Please do the needful. 

FYI, I was able to generate a clean build for Windows.

**Comment by atteneder** [comment]
Hi,

Thanks for your interest and for reporting.

WebGL build is a bit different, since I embed it in a special project via iframe (see [glTFastWebDemo](https://github.com/atteneder/glTFastWebDemo)) which has HTML5 menu (a crappy one, but still) and thus the IMGUI is not shown.

Let me check what I do different.

**Comment by dhawalbanker** [comment]
Thanks @atteneder for the quick reply. 

I read the code and realized that Unity's GUI was #defined only for Editor and not WebGL. Disabling that at least I was able to build the WebGL build with the demo's GUI to navigate around the different scenes.

**Comment by atteneder** [comment]
cool!
