### ISSUE TITLE
error CS0246: The type or namespace name 'SampleSet' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by A9191** [atteneder/glTFastDemo#4]
![error](https://user-images.githubusercontent.com/21275654/141793949-8c0bf789-13c7-481f-86ab-e2739d4d4c6f.JPG)

Unity 2021.2

**Comment by atteneder** [comment]
Hmm, this project turned out to serve my development needs more than it is a demo project. Thus I haven't really paid attention to housekeeping (no errors, works on other machines etc.)

That said, there's been a char-case problem with the `packages` folder that I fixed today. Please give it another try.

While we're at it: what's your intend using this project?
